name: pitest
on:
  workflow_dispatch:
#  push:
#    branches:
#      - '**'
#    paths-ignore:
#      - '**.md'
#      - '**.yml'
#      - '**.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]
        architecture: [ 'x64' ]
    name: Mutation Testing with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
          distribution: 'temurin'

      - name: Run Mutation Testing
        run: mvn clean test -Pmutation-tests -DoutputFormats=html org.pitest:pitest-maven:mutationCoverage

      - name: Copy Pitest Reports to docs folder
        run: |
          mkdir -p docs/pitest-reports
          cp -r target/pit-reports/* docs/pitest-reports/

      - name: Commit Pitest Reports
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Pitest mutation test reports"
          file_pattern: "docs/pitest-reports/**"
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
          push_options: '--force'